Repository StnetixDevTeam/ariADDna, pull requests merged in 2018-03, with the labels that each got.

#133 Fix checkstyle
  doc/codestyle/checkstyle.xml
  vufs/src/main/java/com/stnetix/ariaddna/vufs/VufsConfiguration.java
  vufs/src/main/java/com/stnetix/ariaddna/vufs/service/IVufsService.java
Labels: Area - Build, Issue - Bug, P0, Review - Needed

#134 Fix checkstyle part 2
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/DTO/AccessTokenDTO.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/DTO/CertificateDTO.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/DTO/CloudCredentialsDTO.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/DTO/KeyStorePasswordDTO.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/DTO/UserDTO.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/datetime/DateTime.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/exception/AriaddnaException.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/logger/AriaddnaLogger.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/logger/Marker.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/mavenutil/MavenUtil.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/ui/interfaces/IUi.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/xmlparser/XmlParser.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/xmlparser/exception/XmlParserException.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/xmlparser/handlers/XmlDbSettingHandler.java
  common-utils/src/test/java/com/stnetix/ariaddna/commonutils/datetime/DateTimeTest.java
  common-utils/src/test/java/com/stnetix/ariaddna/commonutils/exception/AriaddnaExceptionTest.java
  common-utils/src/test/java/com/stnetix/ariaddna/commonutils/mavenutil/MavenUtilTest.java
  doc/codestyle/checkstyle.xml
  doc/codestyle/header.idea.txt
  doc/codestyle/header.txt
  keystore-service/src/main/java/com/stnetix/ariaddna/keystore/utils/CertFactory.java
  keystore-service/src/main/java/com/stnetix/ariaddna/keystore/utils/IPersistHelper.java
  keystore-service/src/main/java/com/stnetix/ariaddna/keystore/utils/PersistHelperImpl.java
  keystore-service/src/main/java/com/stnetix/ariaddna/keystore/utils/PersistHelperStubImpl.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/services/AccessTokenServiceImpl.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/services/CertificateServiceImpl.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/services/CloudCredentialsServiceImpl.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/services/IAccessTokenService.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/services/ICertificateService.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/services/ICloudCredentialsService.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/services/IKeyStorePasswordService.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/services/KeyStorePasswordServiceImpl.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/transformers/AccessTokenTransformer.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/transformers/CertificateTransformer.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/transformers/CloudCredentialsTransformer.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/transformers/KeyStorePasswordTransformer.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/transformers/UserTransformer.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/TestHelper.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/services/AccessTokenServiceImplTest.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/services/CertificateServiceImplTest.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/services/CloudCredentialsServiceImplTest.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/services/KeyStorePasswordServiceImplTest.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/transformers/AccessTokenTransformerTest.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/transformers/CertificateTransformerTest.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/transformers/CloudCredentialsTransformerTest.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/transformers/KeyStorePasswordTransformerTest.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/transformers/UserTransformerTest.java
Labels: Area - Build, Issue - Bug, P0, Review - Needed

#136 Fix checkkstyle part 4
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/xmlparser/handlers/XmlDbSettingHandler.java
  notify-server/pom.xml
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/AutoConnectSocket.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/Client.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/ClientMessageProcessor.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/ClientMessageSystem.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/ClientSocketListener.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/ClientSocketService.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/ConfigClient.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/ConfigurationService.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/MyHandler.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/client/PushClientConsumeImpl.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/AriaddnaWebSocket.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/AriaddnaWebSocketCreator.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/ArriaddnaWebSocketServlet.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/ClientInfo.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/ConfigServer.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/IPushConsume.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/IPushProduce.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/JSONServerMessageGenerator.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/MessageGenerator.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/MessageProcessor.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/PushConsumeServerImpl.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/PushProduceServerImpl.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/PushServer.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/Server.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/ServerMessageProcessor.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/ServerMessageSystem.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/SharedMap.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/SharedQueue.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/StringServerMessageGenerator.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/UserService.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/UserServiceImpl.java
  notify-server/src/main/java/com/stnetix/ariaddna/pushnotification/server/WorkerThread.java
  server-core/src/main/java/com/stnetix/ariaddna/servercore/configuration/ServerCoreConfiguration.java
  server-core/src/main/resources/settings.xml
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/entities/UserEntity.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/entities/vufs/AllocationCollection.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/entities/vufs/MetafileEntity.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/entities/vufs/MetatableEntity.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/services/AccessTokenServiceImpl.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/transformers/MetatableTransformer.java
  storage-service/src/main/java/com/stnetix/ariaddna/persistence/utils/JPAConfiguration.java
  storage-service/src/main/resources/settings.xml
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/TestHelper.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/services/MetatableServiceImplTest.java
  storage-service/src/test/java/com/stnetix/ariaddna/persistence/transformers/MetatableTransformerTest.java
Labels: Area - Build, Issue - Bug, P0, Review - Needed

#137 Implementing BMS classes
  block_manipulation_service/pom.xml
  block_manipulation_service/src/main/java/com/stnetix/ariaddna/blockmanipulation/AppConfiguration.java
  block_manipulation_service/src/main/java/com/stnetix/ariaddna/blockmanipulation/BlockGenerate.java
  block_manipulation_service/src/main/java/com/stnetix/ariaddna/blockmanipulation/BlockManipulationApplication.java
  block_manipulation_service/src/main/resources/settings.xml
  block_manipulation_service/src/test/java/com/stnetix/ariaddna/blockmanipulation/BMSConfiguration.java
  block_manipulation_service/src/test/java/com/stnetix/ariaddna/blockmanipulation/BMSTest.java
  block_manipulation_service/src/test/java/com/stnetix/ariaddna/blockmanipulation/LocalService.java
  block_manipulation_service/src/test/java/com/stnetix/ariaddna/blockmanipulation/LocalServiceStub.java
  block_manipulation_service/src/test/java/com/stnetix/ariaddna/blockmanipulation/LocalServiceTest.java
  block_manipulation_service/src/test/resources/settings.xml
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/settings/Settings.java
  common-utils/src/main/java/com/stnetix/ariaddna/commonutils/xmlparser/handlers/BlockManipulationSettingHandler.java
  local-storage-manager/src/main/java/com/stnetix/ariaddna/localstoragemanager/localservice/LocalService.java
  pom.xml
  tmp/block_above.dat
  tmp/block_below.dat
  tmp/block_equal.dat
Labels: Area - VUFS, Issue - Feature, P0, Review - Needed

#140 Add pom file to user-service module
  user-service/pom.xml
Labels: Area - Build, Issue - Bug, P0, Review - Committed
